### ISSUE TITLE
[TODO] TMA 모듈 생성 자동화

### ISSUE THREAD

**Issue by asd8169** [asd8169/tuist-template#21]
**설명**
Micro Features Architecture(TMA) target 적용을 위해 Scaffold 및 Template을 활용한 모듈 생성 자동화를 도입하려 합니다. 모듈 생성 과정을 효율화하고, 일관된 구조를 유지할 수 있도록 합니다.
<img width="580" alt="module" src="https://github.com/user-attachments/assets/e996e794-a33a-43ad-9a6f-5059717bd701">

**체크리스트**
- [x] Scaffold를 활용한 TMA 모듈 생성 스크립트 작성
- [x] Template 기반의 기본 모듈 구성
- [x] 실행 가능한 스크립트 커맨드 추가
- [x] 디렉토리 구조를 코드로 생성(Swift코드로 생성할 수 있는 스크립트 작성)
- [x] makefile 생성 및 구성

**추가 정보**
이 할 일 항목에 대한 기타 정보나 노트를 추가하세요.
