### ISSUE TITLE
[TODO] Tuist Plugin 작업

### ISSUE THREAD

**Issue by asd8169** [asd8169/tuist-template#6]
**설명**
Tuist 프로젝트에 새로운 플러그인을 추가하여 프로젝트 설정 및 관리를 개선하고자 합니다. 이번 작업에서는 플러그인의 설치 및 설정, 그리고 각 모듈에서 플러그인을 활용할 수 있도록 구조를 변경하는 것을 목표로 합니다.

**체크리스트**
- [x] Tuist Plugin 설치 및 설정
- [x] 각 모듈에서 플러그인을 활용할 수 있도록 설정 변경
- [ ] 각 모듈별 테스트 수행 및 검증

**추가 정보**
플러그인이 정상적으로 설치되고 각 모듈에서 활용 가능해야 합니다.
