### ISSUE TITLE
[TODO] Configuration 설정(XCConfig) 등록

### ISSUE THREAD

**Issue by asd8169** [asd8169/tuist-template#7]
**설명**
프로젝트에서 사용할 XCConfig 파일을 설정하고, 각 환경(Development, Staging, Production)에 맞는 설정을 등록합니다. 이를 통해 빌드 및 배포 환경을 쉽게 관리할 수 있도록 합니다. 공통 설정은 Shared.xcconfig 파일에 포함하고, 각 환경별로 필요한 설정은 개별 .xcconfig 파일에 추가합니다.

**체크리스트**
- [ ] Shared.xcconfig 파일 생성
- [ ] Development 환경 설정 등록 (DEV.xcconfig)
- [ ] Staging 환경 설정 등록 (STAGE.xcconfig)
- [ ] Production 환경 설정 등록 (PROD.xcconfig)
- [ ] 각 환경에 맞는 설정 값 추가

**추가 정보**
환경별로 필요한 설정 값(예: API 엔드포인트, 빌드 플래그 등)을 정리하고, Shared.xcconfig 파일과 개별 .xcconfig 파일에 추가합니다.
